from selenium.webdriver.common.by import By

from_field = (By.ID, 'from')
to_field = (By.ID, 'to')
request_taxi_button = (By.CSS_SELECTOR, ".button.round")
comfort_rate_icon = (By.XPATH, "//div[@class='tcard-title' and text ()='Comfort']")
phone_field_button = (By.CSS_SELECTOR, "np-button")
phone_field = (By.ID, 'phone')
next_button = (By.CSS_SELECTOR, "button.button.full")
confirm_button = (By.XPATH, "//div[@class='button.button.full' and text ()='Confirmar']")
payment_method_button = (By.CSS_SELECTOR, ".pp-button.filled")
add_card_button = (By.CSS_SELECTOR, "pp-title")
card_text = (By.CSS_SELECTOR, "input#number.card-input")
card_code = (By.ID, "code")
message_for_driver_button = (By.ID, "input-container")
message_for_driver_text = (By.ID, "comment")
reqs_button = (By.CSS_SELECTOR, "reqs-header")
blanket_button = (By.XPATH, "//div[@class='r-sw-label' and text ()='Manta y pañuelos']")
ice_cream_label = (By.XPATH, "//div[@class='r-counter-label' and text ()='Helado']")
slider_button = (By.CSS_SELECTOR, "span.slider.round")
plus_button = (By.CSS_SELECTOR, "counter-plus")
final_blue_button = (By.CSS_SELECTOR, "span.smart-button-main")
